### PR TITLE
Generate and write API docs directly in api_docs.md instead of using JSON

### PR DESCRIPTION
**Pull request by Vivekkumar-IN**

### CODE REVIEW

**Comment by PaulSonOfLars** [comment]
Hi,

Can you please explain the rationale behind this PR? You haven't set a PR description, we haven't discussed these changes offline, and I'm not sure I understand what your changes are hoping to achieve.

From what I can see, you have:
- Removed the entirety of the JSON output, which means the spec is no longer machine readable - which is what this repo aims to achieve.
- Turned the JSON spec into markdown; what is this aiming to achieve? We already have a human-readable version on the normal bot API docs site. 
- Removed all the comments from the scraping script, reducing readability.
- Removed arbitrary newlines, many of which were there to conform with python style guides https://peps.python.org/pep-0008/#blank-lines

As it stands, I can't accept a PR this big without any sort of explanation for the reasoning behind it.

**Comment by Vivekkumar-IN** [comment]
Hi,

Thank you for your feedback and for pointing out these important aspects. I apologize for not providing a detailed description earlier.

### Rationale Behind Changes:

My main intention was to improve the readability of the project for users who prefer Markdown over JSON. I aimed to make the documentation more accessible to those who might not require machine-readability, but I now understand that the JSON spec is crucial for the primary objective of this repository.

### Plan for Reintroducing Comments and Style:

Based on your feedback, I will reintroduce the comments and blank lines that were aligned with PEP 8 style guides. I will ensure that the script's readability is maintained, and that any changes made for Markdown are confined only to the documentation, without affecting the core JSON spec or the script itself.

### Conclusion and Apology:

If these changes don't fit with your project's goals or approach, I fully understand, and you're welcome to decline the PR. Again, I apologize for the oversight, and I truly appreciate the opportunity to contribute.

**Comment by PaulSonOfLars** [comment]
Closing because this is clearly AI slop.

**Comment by Vivekkumar-IN** [comment]
Hi @PaulSonOfLars ,

Sorry for the confusion caused by my pull request.

At that time, I didn’t fully understand the purpose of this repository. I thought it was mainly for providing bot API examples and didn’t realize the importance of keeping a machine-readable JSON spec. I also didn’t know that the official documentation is available separately on Telegram’s website.

Now I understand the goals of this repository and why the original structure is important. I apologize for my mistake and for wasting your time.

Thank you for maintaining this project and for your feedback.

**Pull request closed without merging**
